### ISSUE TITLE
Default metrics dashboards

### ISSUE THREAD

**Issue by estolfo** [elastic/elastic-otel-python#24]
Let's make sure metrics dashboards are shown for the OTel distro in the Metrics tab and that the metrics shown are meaningful. This task might also require some UI task coordination and portable dashboard work.
If work was done for [this issue](https://github.com/elastic/apm/issues/806), it's possible some of it could be reused.

**Comment by nithinbsFaro** [comment]
Hey @xrmx can you please provide an example code snippet to implement opentelemetry-instrumentation-system-metrics in python code? Thanks in advance.
